/** Noms d icones MaterialCommunityIcons pour l app mobile. */
export const icons = {
  tabCalls: "phone-in-talk",
  tabMessages: "voicemail",
  tabDialer: "dialpad",
  tabSettings: "cog-outline",
  trusted: "shield-account",
  contacts: "contacts-outline",
  incoming: "phone-incoming",
  outgoing: "phone-outgoing",
  offline: "cloud-off-outline",
  syncOk: "check-circle",
  hangup: "phone-hangup",
  qrScan: "qrcode-scan",
  wifiAlert: "wifi-alert",
  wifi: "wifi",
  play: "play",
  pause: "pause",
  close: "close",
  recall: "phone-outgoing",
} as const;
